version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=server=db;port=3306;database=mydb;user=myuser;password=mypassword

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
